[project]
name = "ats"
version = "0.0.1"
authors = [
  { name="Johnny Chen", email="johnnychen762@gmail.com" },
]
description = "Automated trading system"
readme = "README.rst"
license = { text="MIT" }
requires-python = ">=3.8"
classifiers = [
        'Development Status :: 1 - Dev/Alpha',

        # Indicate who your project is intended for
        'Intended Audience :: Developers',
        'Topic :: Software Development',

        # Pick your license as you wish (should match "license" above)
        'License :: OSI Approved :: MIT License',

        # Specify the Python versions you support here.
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["src"]

[project.urls]
"Homepage" = "https://github.com/MathTypes/ats"
"Bug Tracker" = "https://github.com/MathTypes/ats/issues"
