
[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Jianjun Chen <jianjun00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "1.24.4"
torch = "2.0.1"
hydra = "^2.5"
omegaconf = "^2.3.0"
pandas-market-calendars = "^4.1.4"
empyrical = "^0.5.5"
lightning = "^2.0.5"
optuna = "^3.2.0"
pyarrow = "^12.0.1"
ray = "^2.5.1"
ta = "^0.10.2"
plotly = "^5.15.0"
pytorch-optimizer = "^2.11.0"
wandb = "0.15.3"
dask = "2023.5.0"
ray-lightning = "^0.3.0"
hydra-core = "^1.3.2"
transformers = "^4.30.2"

[project]
name = "src"
version = "0.0.1"
authors = [
  { name="Johnny Chen", email="johnnychen762@gmail.com" },
]
description = "Automated trading system"
readme = "README.rst"
license = { text="MIT" }
requires-python = ">=3.8"
classifiers = [
        'Development Status :: 1 - Dev/Alpha',

        # Indicate who your project is intended for
        'Intended Audience :: Developers',
        'Topic :: Software Development',

        # Pick your license as you wish (should match "license" above)
        'License :: OSI Approved :: MIT License',

        # Specify the Python versions you support here.
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools]
py-modules = ["src"]

[project.urls]
"Homepage" = "https://github.com/MathTypes/ats"
"Bug Tracker" = "https://github.com/MathTypes/ats/issues"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
