
[tool.poetry]
name = "ats"
version = "0.1.0"
description = ""
authors = ["Jianjun Chen <jianjun00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[project]
name = "ats"
version = "0.0.1"
authors = [
  { name="Johnny Chen", email="johnnychen762@gmail.com" },
]
description = "Automated trading system"
readme = "README.rst"
license = { text="MIT" }
requires-python = ">=3.8"
classifiers = [
        'Development Status :: 1 - Dev/Alpha',

        # Indicate who your project is intended for
        'Intended Audience :: Developers',
        'Topic :: Software Development',

        # Pick your license as you wish (should match "license" above)
        'License :: OSI Approved :: MIT License',

        # Specify the Python versions you support here.
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools]
py-modules = ["src"]

[project.urls]
"Homepage" = "https://github.com/MathTypes/ats"
"Bug Tracker" = "https://github.com/MathTypes/ats/issues"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
