device: cuda
mode: train

train_start_date: 2009-06-01
eval_start_date: 2020-01-01
eval_end_date: 2023-07-28
test_start_date: 2020-01-01
test_end_date: 2023-07-28
time_interval_minutes: 30

market: CME_Equity
workers: 8
num_tune_iter: 20
max_epochs: 50
log_mode: All
eval_batches: 6
tune_learning_rate: False
log_example_eval_every_n_epochs: 1
tag: ${job.mode}
checkpoint:
