apiVersion: batch/v1
kind: Job
metadata:
  name: ib-fut-trade
  namespace: ib-trading
spec:
  template:
    metadata:
      name: ib-fut-trade
    spec:
      hostname: ib-fut-trade-1
      hostNetwork: true
      containers:
      - name: ib-fut-trade
        image: gcr.io/keen-rhino-386415/akolotech/twitter_app:v1.9
        env:
        - name: SYMBOLS
          value: "ES,NQ,RTY,CL,GC,SI,ZN,ZT"
        - name: IB_HOST
          value: 10.16.2.63
        - name: PYTHONPATH
          value: .
        - name: FIREBASE_CERT
          value: "/opt/ats/secrets/keen-rhino-386415-firebase-adminsdk-9jpg7-968c43811b.json"
        command: ["python3", "ib/firebase_fut.py", "ES,NQ,RTY,GC,SI,ZN,ZT,CL",  "-p=4001",  "--size=1 min", "-t=TRADES", "--host=10.138.0.8",  "--security-type=FUT", "--firebase_cert=/opt/ats/secrets/keen-rhino-386415-firebase-adminsdk-9jpg7-968c43811b.json"]
      restartPolicy: Never
  backoffLimit: 4
