static_categoricals: ["ticker"]
time_varying_known_reals: ["hour_of_day", "day_of_week", "day_of_month"]

# _ff comes from past while _bf comes from future. Features should only use past and label should use futures
time_varying_unknown_reals: ["close_back", "volume_back", "close", "high", "low", "open", "close_back_cumsum", "close_high_21_ff", "close_low_21_ff", "close_high_51_ff", "close_low_51_ff", "close_low_201_ff", "close_high_201_ff", "macd_8_24", "macd_16_48", "macd_32_96"]
lags: {"close_high_21_ff":[21], "close_low_21_ff":[21], "close_high_51_ff":[51], "close_low_51_ff":[51], "close_back_cumsum":[1], "close_low_201_ff":[201], "close_high_201_ff":[201], "close":[1], "high":[1], "low":[1], "open":[1], "volume_back":[1], "close_back":[1], "macd_8_24":[1], "macd_16_48":[1], "macd_32_96":[1],}
add_relative_time_idx: True