hidden_size: 20
prediction_length: 46
context_length: 230
patch_len: 6
stride: 3
d_model: 64
train_batch_size: 256
eval_batch_size: 64
learning_rate: 0.03
attn_heads : 8
dropout: 0.3
gradient_clip_val: 0.4
accumulate_grad_batches: 8192
attn_dropout: 0.3
n_layers: 5
lstm_layers: 7
multitask: True
heads:
  - prediction
  - returns_daily_prediction
  #- time_daily_prediction
prediction:
  loss_name: SMAPE
  target: ["close_back"]
  logging_metrics: ["SMAPE", "MAE", "RMSE", "MAPE", "MASE"]
returns_daily_prediction:
  loss_name: SMAPE
  target: ["ret_from_low_1d_shift_1d", "ret_from_high_1d_shift_1d"]
  logging_metrics: ["SMAPE", "MAE", "RMSE", "MAPE", "MASE"]
time_daily_prediction:
  loss_name: SMAPE
  target: ["time_to_low_1d_ff_shift_1d","time_to_high_1d_ff_shift_1d"]
  logging_metrics: ["SMAPE", "MAE", "RMSE", "MAPE", "MASE"]
vol_prediction:
  #loss_name: MQF2DistributionLoss
  loss_name: SMAPE
  target: "daily_vol"
  logging_metrics: ["SMAPE", "MAE", "RMSE", "MAPE", "MASE"]
anomaly_returns:
  loss_name: SMAPE
  target: "close_back_cumsum"
  logging_metrics: []
name: patch_tft_supervised

checkpoint:
checkpoint_output_dir: ${hydra:runtime.cwd}/model

features:
  static_categoricals: ["ticker"]
  time_varying_known_reals: ["hour_of_day", "day_of_week", "day_of_month","time_to_new_york_open", "time_to_new_york_close", "time_to_london_open","time_to_london_close","time_to_last_macro_event_imp1","time_to_next_macro_event_imp1","time_to_last_macro_event_imp2","time_to_next_macro_event_imp2","time_to_last_macro_event_imp3","time_to_next_macro_event_imp3","time_to_weekly_close","time_to_monthly_close","time_to_option_expiration","time_to_new_york_last_open","time_to_london_last_open"]
  time_varying_unknown_reals: ["close_back", "volume_back", "high_back", "low_back", "open_back", "ret_from_high_5", "ret_from_low_5", "ret_from_high_11", "ret_from_low_11","ret_from_high_21", "ret_from_low_21", "ret_from_high_51", "ret_from_low_51", "ret_from_low_201", "ret_from_high_201", "ret_from_high_5d", "ret_from_low_5d", "ret_from_high_11d", "ret_from_low_11d","ret_from_high_21d", "ret_from_low_21d", "ret_from_high_51d", "ret_from_low_51d", "ret_from_low_201d", "ret_from_high_201d", "macd_8_24", "macd_16_48", "macd_32_96", "macd", "macd_signal", "ret_from_bb_high_5_2", "ret_from_bb_low_5_2", "ret_from_bb_high_5_3", "ret_from_bb_low_5_3", "ret_from_bb_high_10_2", "ret_from_bb_low_10_2", "ret_from_bb_high_10_3", "ret_from_bb_low_10_3", "ret_from_bb_high_20_2", "ret_from_bb_low_20_2", "ret_from_bb_high_20_3","ret_from_bb_low_20_3", "ret_from_bb_high_50_2", "ret_from_bb_low_50_2", "ret_from_bb_high_50_3", "ret_from_bb_low_50_3", "ret_from_bb_high_100_2", "ret_from_bb_low_100_2", "ret_from_bb_high_100_3", "ret_from_bb_low_100_3", "ret_from_bb_high_200_2", "ret_from_bb_low_200_2", "ret_from_bb_high_200_3", "ret_from_bb_low_200_3", "ret_from_sma_5", "ret_from_sma_10","ret_from_sma_20","ret_from_sma_50","ret_from_sma_100","ret_from_sma_200", "ret_from_sma_5d", "ret_from_sma_10d","ret_from_sma_20d","ret_from_sma_50d","ret_from_sma_100d","ret_from_sma_200d","time_to_high_5_ff", "time_to_low_5_ff", "time_to_high_11_ff", "time_to_low_11_ff", "time_to_high_21_ff", "time_to_low_21_ff", "time_to_high_51_ff", "time_to_low_51_ff", "time_to_high_201_ff", "time_to_low_201_ff","time_to_high_5d_ff", "time_to_low_5d_ff", "time_to_high_11d_ff", "time_to_low_11d_ff", "time_to_high_21d_ff", "time_to_low_21d_ff", "time_to_high_51d_ff", "time_to_low_51d_ff", "time_to_high_201d_ff", "time_to_low_201d_ff", "ret_from_vwap_since_london_open","ret_from_vwap_since_new_york_open","ret_from_vwap_since_last_macro_event_imp1","ret_from_vwap_around_macro_event_imp1","ret_from_vwap_since_last_macro_event_imp2","ret_from_vwap_around_macro_event_imp2","ret_from_vwap_since_last_macro_event_imp3","ret_from_vwap_around_macro_event_imp3","ret_from_vwap_around_new_york_open","ret_from_vwap_around_london_open","ret_from_vwap_around_new_york_close","ret_from_vwap_around_london_close","macd_8_24_day", "macd_16_48_day", "macd_32_96_day","daily_vol", "daily_returns","daily_skew","daily_kurt","daily_vol_5", "daily_returns_5","daily_skew_5","daily_kurt_5", "daily_kurt","daily_vol_10","daily_returns_10","daily_skew_10","daily_kurt_10","daily_vol_20", "daily_returns_20","daily_skew_20","daily_kurt_20","ret_from_bb_high_5d_2", "ret_from_bb_low_5d_2", "ret_from_bb_high_5d_3", "ret_from_bb_low_5d_3", "ret_from_bb_high_10d_2", "ret_from_bb_low_10d_2", "ret_from_bb_high_10d_3", "ret_from_bb_low_10d_3", "ret_from_bb_high_20d_2", "ret_from_bb_low_20d_2", "ret_from_bb_high_20d_3","ret_from_bb_low_20d_3", "ret_from_bb_high_50d_2", "ret_from_bb_low_50d_2", "ret_from_bb_high_50d_3", "ret_from_bb_low_50d_3", "ret_from_bb_high_100d_2", "ret_from_bb_low_100d_2", "ret_from_bb_high_100d_3", "ret_from_bb_low_100d_3", "ret_from_bb_high_200d_2", "ret_from_bb_low_200d_2", "ret_from_bb_high_200d_3", "ret_from_bb_low_200d_3","daily_vol", "daily_returns_1d","daily_skew_1d","daily_kurt_1d","daily_vol_5d", "daily_returns_5d","daily_skew_5d","daily_kurt_5d", "daily_kurt_1d","daily_vol_10d","daily_returns_10d","daily_skew_10d","daily_kurt_10d","daily_vol_20d", "daily_returns_20d","daily_skew_20d","daily_kurt_20d","rsi_14","rsi_28","rsi_42","rsi_14d","rsi_28d","rsi_42d","time_to_high_1d_ff","time_to_low_1d_ff","ret_from_high_1d","ret_from_low_1d","ret_from_high_1d_shift_1d","ret_from_low_1d_shift_1d","time_to_high_1d_ff_shift_1d","time_to_low_1d_ff_shift_1d"]
  #lags: {"ret_from_high_1d_shift_1d":[46],"ret_from_low_1d_shift_1d":[46],"time_to_high_1d_ff_shift_1d":[46],"time_to_low_1d_ff_shift_1d":[46]}
  lags: {}
  add_relative_time_idx: True
  add_macro_event: True
  add_daily_rolling_features: True

max_lag: 365
max_lead: 7

