hidden_size: 4
prediction_length: 32
context_length: 640
patch_len: 32
stride: 16
d_model: 4
train_batch_size: 1024
eval_batch_size: 128
learning_rate: 0.02
attn_heads : 4
attn_dropout: 0.1
multitask: True
heads:
  - returns_prediction
#  - position_optimization
returns_prediction:
  loss_name: MQF2DistributionLoss
  target: "close_back"
  logging_metrics: ["SMAPE", "MAE", "RMSE", "MAPE", "MASE"]
position_optimization:
  loss_name: SharpeLoss
  target: "close_back"
  logging_metrics: []
name: patch_tft_supervised
#time_varying_known_reals: ["relative_time_idx", "daily_vol", "macd_8_24", "macd_16_48", "macd_32_96"]
time_varying_known_reals: ["daily_vol",  "hour_of_day", "day_of_week", "day_of_month"]
time_varying_unknown_reals: ["close_back", "volume_back"]
add_relative_time_idx: True