hidden_size: 8
prediction_length: 4
context_length: 32
patch_len: 2
stride: 1
d_model: 8
train_batch_size: 4096
eval_batch_size: 1024
learning_rate: 0.02
attn_heads : 4
attn_dropout: 0.1
multitask: True
heads:
  - returns_prediction
#  - position_optimization
returns_prediction:
  loss_name: MQF2DistributionLoss
  #loss_name: QuantileLoss
  target: "close_back"
  logging_metrics: ["SMAPE", "MAE", "RMSE", "MAPE", "MASE"]
position_optimization:
  loss_name: SharpeLoss
  # TODO: figure out how to allow multi loss when same targets are
  # used in different heads.
  target: "close_back_cumsum"
  logging_metrics: []
name: patch_tft_supervised
