// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWKwtEp4spSafz20TRrOj8rrjbL4KcwI0',
    appId: '1:315214571397:web:cd97619b38d679e288c6ec',
    messagingSenderId: '315214571397',
    projectId: 'keen-rhino-386415',
    authDomain: 'keen-rhino-386415.firebaseapp.com',
    databaseURL: 'https://keen-rhino-386415-default-rtdb.firebaseio.com',
    storageBucket: 'keen-rhino-386415.appspot.com',
    measurementId: 'G-SREB9X0HYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMF0e1vnDRxKWtwJuaXEHmwsqAU_uVmHc',
    appId: '1:315214571397:android:7857d9f94d2d30e788c6ec',
    messagingSenderId: '315214571397',
    projectId: 'keen-rhino-386415',
    databaseURL: 'https://keen-rhino-386415-default-rtdb.firebaseio.com',
    storageBucket: 'keen-rhino-386415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFzfjmcJn4zmkKQhARvaFqRF2Eqpal3EY',
    appId: '1:315214571397:ios:31123623074b7f0b88c6ec',
    messagingSenderId: '315214571397',
    projectId: 'keen-rhino-386415',
    databaseURL: 'https://keen-rhino-386415-default-rtdb.firebaseio.com',
    storageBucket: 'keen-rhino-386415.appspot.com',
    iosClientId:
        '315214571397-fg6j8kesead0fgjpqu2ugtopbrh2up92.apps.googleusercontent.com',
    iosBundleId: 'com.akolotech.finbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFzfjmcJn4zmkKQhARvaFqRF2Eqpal3EY',
    appId: '1:315214571397:ios:ef9613e4489c6ea088c6ec',
    messagingSenderId: '315214571397',
    projectId: 'keen-rhino-386415',
    databaseURL: 'https://keen-rhino-386415-default-rtdb.firebaseio.com',
    storageBucket: 'keen-rhino-386415.appspot.com',
    iosClientId:
        '315214571397-liiqnme6c0acdrkvva1ctvjuideg9com.apps.googleusercontent.com',
    iosBundleId: 'com.akolotech.finbot',
  );
}
