FROM zedeus/nitter:2c6cabb4abe79166ce9973d8652fb213c1b0c5a2

ADD . /opt/ats/

ENV FIREBASE_CERT=/opt/ats/secrets/keen-rhino-386415-firebase-adminsdk-9jpg7-968c43811b.json
ENV TWITTER_LOGIN=AlexSimon190658
ENV TWITTER_SYMBOLS=spy,qqq,vix,uso,gld,vix,iwm,tsla,appl,nvda,msft,goog
ENV TWITTER_USER_PROFILE=/opt/ats
ENV TWITTER_ROWS=100
