name: test_runner
on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  workflow_call:
  workflow_dispatch:
    
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
        
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest coveralls
          pip install .
          
      - name: List dependencies
        run: |
          pip freeze
                
      - name: run tests
        run: |          
          coverage run --source=src -m pytest tests
          coverage lcov -o coverage.lcov
          
   
